/* Copyright 2017-present The KotlinNLP Authors. All Rights Reserved.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 * ------------------------------------------------------------------*/

package com.kotlinnlp.linguisticdescription.morphology.morphologies.relations

import com.kotlinnlp.linguisticdescription.morphology.POS
import com.kotlinnlp.linguisticdescription.morphology.SingleMorphology

/**
 * The 'conjunction' morphology.
 *
 * @param pos the POS of this morphology
 */
sealed class Conjunction(pos: POS) : SingleMorphology(pos), Relation {

  /**
   * The 'conjunction' morphology.
   *
   * @property lemma the lemma
   * @property oov whether this morphology has been automatically generated by the system (Out Of Vocabulary)
   */
  class Base(override val lemma: String, override val oov: Boolean) : Conjunction(POS.Conj)

  /**
   * The 'comparative conjunction' morphology.
   *
   * @param pos the POS of this morphology
   */
  sealed class Comparative(pos: POS) : Conjunction(pos) {

    /**
     * The 'comparative conjunction' morphology.
     *
     * @property lemma the lemma
     * @property oov whether this morphology has been automatically generated by the system (Out Of Vocabulary)
     */
    class Base(override val lemma: String, override val oov: Boolean) : Comparative(POS.ConjCompar)

    /**
     * The 'antecedent comparative conjunction' morphology.
     *
     * @property lemma the lemma
     * @property oov whether this morphology has been automatically generated by the system (Out Of Vocabulary)
     */
    class Antecedent(override val lemma: String, override val oov: Boolean) : Comparative(POS.ConjComparAntec)

    /**
     * The 'successive comparative conjunction' morphology.
     *
     * @property lemma the lemma
     * @property oov whether this morphology has been automatically generated by the system (Out Of Vocabulary)
     */
    class Successive(override val lemma: String, override val oov: Boolean) : Comparative(POS.ConjComparSucc)
  }

  /**
   * The 'concessive conjunction' morphology.
   *
   * @property lemma the lemma
   * @property oov whether this morphology has been automatically generated by the system (Out Of Vocabulary)
   */
  class Concessive(override val lemma: String, override val oov: Boolean) : Conjunction(POS.ConjConcess)

  /**
   * The 'coordinating conjunction' morphology.
   *
   * @param pos the POS of this morphology
   */
  sealed class Coordinating(pos: POS) : Conjunction(pos) {

    /**
     * The 'coordinating conjunction' morphology.
     *
     * @property lemma the lemma
     * @property oov whether this morphology has been automatically generated by the system (Out Of Vocabulary)
     */
    class Base(override val lemma: String, override val oov: Boolean) : Coordinating(POS.ConjCoord)

    /**
     * The 'adversative coordinating conjunction' morphology.
     *
     * @property lemma the lemma
     * @property oov whether this morphology has been automatically generated by the system (Out Of Vocabulary)
     */
    class Adversative(override val lemma: String, override val oov: Boolean) : Coordinating(POS.ConjCoordAdvers)

    /**
     * The 'disjunctive coordinating conjunction' morphology.
     *
     * @property lemma the lemma
     * @property oov whether this morphology has been automatically generated by the system (Out Of Vocabulary)
     */
    class Disjunctive(override val lemma: String, override val oov: Boolean) : Coordinating(POS.ConjCoordDisj)

    /**
     * The 'explicit coordinating conjunction' morphology.
     *
     * @property lemma the lemma
     * @property oov whether this morphology has been automatically generated by the system (Out Of Vocabulary)
     */
    class Explicit(override val lemma: String, override val oov: Boolean) : Coordinating(POS.ConjCoordExplic)

    /**
     * The 'negative coordinating conjunction' morphology.
     *
     * @property lemma the lemma
     * @property oov whether this morphology has been automatically generated by the system (Out Of Vocabulary)
     */
    class Negative(override val lemma: String, override val oov: Boolean) : Coordinating(POS.ConjCoordNeg)
  }

  /**
   * The 'correlating conjunction' morphology.
   *
   * @param pos the POS of this morphology
   */
  sealed class Correlating(pos: POS) : Conjunction(pos) {

    /**
     * The 'correlating conjunction' morphology.
     *
     * @property lemma the lemma
     * @property oov whether this morphology has been automatically generated by the system (Out Of Vocabulary)
     */
    class Base(override val lemma: String, override val oov: Boolean) : Correlating(POS.ConjCorrel)

    /**
     * The 'successive correlating conjunction' morphology.
     *
     * @property lemma the lemma
     * @property oov whether this morphology has been automatically generated by the system (Out Of Vocabulary)
     */
    class Successive(override val lemma: String, override val oov: Boolean) : Correlating(POS.ConjCorrelSucc)

    /**
     * The 'antecedent correlating conjunction' morphology.
     *
     * @property lemma the lemma
     * @property oov whether this morphology has been automatically generated by the system (Out Of Vocabulary)
     */
    class Antecedent(override val lemma: String, override val oov: Boolean) : Correlating(POS.ConjCorrelAntec)
  }

  /**
   * The 'subordinating conjunction' morphology.
   *
   * @param pos the POS of this morphology
   */
  sealed class Subordinating(pos: POS) : Conjunction(pos) {

    /**
     * The 'subordinating conjunction' morphology.
     *
     * @property lemma the lemma
     * @property oov whether this morphology has been automatically generated by the system (Out Of Vocabulary)
     */
    class Base(override val lemma: String, override val oov: Boolean) : Subordinating(POS.ConjSubord)

    /**
     * The 'adversative subordinating conjunction' morphology.
     *
     * @property lemma the lemma
     * @property oov whether this morphology has been automatically generated by the system (Out Of Vocabulary)
     */
    class Adversative(override val lemma: String, override val oov: Boolean) : Subordinating(POS.ConjSubordAdvers)

    /**
     * The 'interrogativesubordinating ' morphology.
     *
     * @property lemma the lemma
     * @property oov whether this morphology has been automatically generated by the system (Out Of Vocabulary)
     */
    class Interrogative(override val lemma: String, override val oov: Boolean) : Subordinating(POS.ConjSubordInterr)
  }
}
